name: Build And Test
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:

      - name: Cache checked out repo
        uses: actions/cache@v3
        with:
          path: ${{ runner.workspace }}/
          key: ${{ runner.os }}-repo-${{ hashFiles('go.mod') }}
          restore-keys: |
            ${{ runner.os }}-repo-

      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache Go installation
        uses: actions/cache@v3
        with:
          path: /opt/hostedtoolcache/go/1.19.13/x64/
          key: ${{ runner.os }}-go-hash
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Set-Up Go
        id: setup-go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Get go version
        run: go version

  build-and-test:
    needs: prepare
    runs-on: ubuntu-latest
    steps:

      - name: Restore checked out repo from previous job
        uses: actions/cache@v3
        with:
          path: ${{ runner.workspace }}/
          key: ${{ runner.os }}-repo-${{ hashFiles('go.mod') }}

      - name: Restore Go installation from previous job
        uses: actions/cache@v3
        with:
          path: /opt/hostedtoolcache/go/1.19.13/x64/
          key: ${{ runner.os }}-go-hash

      - name: Get go ver
        run: ${{ needs.prepare.outputs.go-path }}/bin/go version

      - name: Build and Check Race
        run: go build -v -race .

      - name: Unit Test
        run: go test -v ./...