name: Build And Test

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      commit-sha: ${{ steps.get-commit-sha.outputs.commit-sha}}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest commit SHA
        id: "get-commit-sha"
        run: echo "commit-sha=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"

      - name: Cache checked out repo
        uses: actions/cache@v3
        with:
          path: ${{ runner.workspace }}/
          key: ${{ runner.os }}-${{ github.repository }}-repo-${{ steps.get-commit-sha.outputs.commit-sha}}

      - name: Set-up Go
        id: setup-go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache: true

  build-and-test:
    needs: prepare
    runs-on: ubuntu-latest
    steps:

      - name: Restore checked out repo from previous job
        uses: actions/cache@v3
        with:
          path: ${{ runner.workspace }}/
          key: ${{ runner.os }}-${{ github.repository }}-repo-${{ needs.prepare.outputs.commit-sha }}

      - name: Restore Go set-up from previous job
        id: setup-go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: Cache/restore build dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-${{ github.repository }}-godeps-${{ hashFiles('go.mod') }}

      - name: Build and Check Race
        run: go build -v -race .

      - name: Unit Test
        run: go test -v ./...